<?xml version="1.0" encoding="UTF-8"?><testrun name="TestRunner (1)" project="OpenWheatherBDDFramework" tests="4" started="4" failures="0" errors="4" ignored="1">
  <testsuite name="com.openweather.runner.TestRunner" time="0.053">
    <testsuite name="Feature: Label verification on Home Page" time="0.053">
      <testsuite name="Scenario: Error_Message_Verification" time="0.013" incomplete="true">
        <error>java.lang.NullPointerException&#13;
	at com.openweather.stepdefinition.HomePageSteps.user_on_homepage(HomePageSteps.java:21)&#13;
	at ✽.Then User already on Home Page(E:/OpenWheather/OpenWheatherBDDFramework/src/main/java/com/openweather/feature/verifyhomepage.feature:6)&#13;
&#13;
cucumber.api.PendingException: TODO: implement me&#13;
	at cucumber.runtime.junit.JUnitReporter.addFailure(JUnitReporter.java:150)&#13;
	at cucumber.runtime.junit.JUnitReporter.addFailureOrIgnoreStep(JUnitReporter.java:138)&#13;
	at cucumber.runtime.junit.JUnitReporter.result(JUnitReporter.java:98)&#13;
	at cucumber.runtime.Runtime.runStep(Runtime.java:282)&#13;
	at cucumber.runtime.model.StepContainer.runStep(StepContainer.java:44)&#13;
	at cucumber.runtime.model.StepContainer.runSteps(StepContainer.java:39)&#13;
	at cucumber.runtime.model.CucumberScenario.run(CucumberScenario.java:44)&#13;
	at cucumber.runtime.junit.ExecutionUnitRunner.run(ExecutionUnitRunner.java:102)&#13;
	at cucumber.runtime.junit.FeatureRunner.runChild(FeatureRunner.java:63)&#13;
	at cucumber.runtime.junit.FeatureRunner.runChild(FeatureRunner.java:18)&#13;
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)&#13;
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)&#13;
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)&#13;
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)&#13;
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)&#13;
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)&#13;
	at cucumber.runtime.junit.FeatureRunner.run(FeatureRunner.java:70)&#13;
	at cucumber.api.junit.Cucumber.runChild(Cucumber.java:95)&#13;
	at cucumber.api.junit.Cucumber.runChild(Cucumber.java:38)&#13;
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)&#13;
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)&#13;
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)&#13;
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)&#13;
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)&#13;
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)&#13;
	at cucumber.api.junit.Cucumber.run(Cucumber.java:100)&#13;
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)&#13;
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)&#13;
&#13;
</error>
        <testcase name="Given user opens browser" classname="Scenario: Error_Message_Verification" time="0.011"/>
        <testcase name="Then User already on Home Page" classname="Scenario: Error_Message_Verification" time="0.002">
          <error>java.lang.NullPointerException&#13;
	at com.openweather.stepdefinition.HomePageSteps.user_on_homepage(HomePageSteps.java:21)&#13;
	at ✽.Then User already on Home Page(E:/OpenWheather/OpenWheatherBDDFramework/src/main/java/com/openweather/feature/verifyhomepage.feature:6)&#13;
&#13;
</error>
        </testcase>
        <testcase name="Then User enters invalid CityName" classname="Scenario: Error_Message_Verification" time="0.002" ignored="true"/>
        <testcase name="Then User closes the application" classname="Scenario: Error_Message_Verification" time="0.0">
          <error>cucumber.api.PendingException: TODO: implement me&#13;
	at cucumber.runtime.junit.JUnitReporter.addFailure(JUnitReporter.java:150)&#13;
	at cucumber.runtime.junit.JUnitReporter.addFailureOrIgnoreStep(JUnitReporter.java:138)&#13;
	at cucumber.runtime.junit.JUnitReporter.result(JUnitReporter.java:98)&#13;
	at cucumber.runtime.Runtime.runStep(Runtime.java:282)&#13;
	at cucumber.runtime.model.StepContainer.runStep(StepContainer.java:44)&#13;
	at cucumber.runtime.model.StepContainer.runSteps(StepContainer.java:39)&#13;
	at cucumber.runtime.model.CucumberScenario.run(CucumberScenario.java:44)&#13;
	at cucumber.runtime.junit.ExecutionUnitRunner.run(ExecutionUnitRunner.java:102)&#13;
	at cucumber.runtime.junit.FeatureRunner.runChild(FeatureRunner.java:63)&#13;
	at cucumber.runtime.junit.FeatureRunner.runChild(FeatureRunner.java:18)&#13;
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)&#13;
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)&#13;
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)&#13;
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)&#13;
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)&#13;
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)&#13;
	at cucumber.runtime.junit.FeatureRunner.run(FeatureRunner.java:70)&#13;
	at cucumber.api.junit.Cucumber.runChild(Cucumber.java:95)&#13;
	at cucumber.api.junit.Cucumber.runChild(Cucumber.java:38)&#13;
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)&#13;
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)&#13;
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)&#13;
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)&#13;
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)&#13;
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)&#13;
	at cucumber.api.junit.Cucumber.run(Cucumber.java:100)&#13;
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)&#13;
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)&#13;
&#13;
</error>
        </testcase>
      </testsuite>
    </testsuite>
  </testsuite>
</testrun>
